msix_config:
  display_name: PicGuard
  publisher_display_name: PUBLISHER_NAME_PLACEHOLDER
  identity_name: IDENTITY_NAME_PLACEHOLDER
  msix_version: 1.0.0.0
#  logo_path: C:\path\to\logo.png
  languages: zh, en
  store: true
  certificate_path: CERTIFICATE_PATH_PLACEHOLDER
  certificate_password: CERTIFICATE_PASSWORD_PLACEHOLDER
  publisher: PUBLISHER_PLACEHOLDER
