name: picguard
version: 1.0.0
summary: Your pictures, your signature.
description: Your pictures, your signature.
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

confinement: strict
base: core22
grade: stable

slots:
  dbus-picguard: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.kjxbyz.watermarkassistant # adjust accordingly to your app name and

apps:
  picguard:
    command: picguard
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
    slots:
      - dbus-picguard
parts:
  picguard:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
#    override-build: | # https://forum.snapcraft.io/t/issue-while-packaging-snap/33693
#      craftctl default
#      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
#      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/usr/bin/picguard"
