name: picguard
version: 1.0.0
summary: Your pictures, your signature.
description: Your pictures, your signature.
icon: snap/gui/picguard.png
title: PicGuard
contact: kjxbyz@163.com
license: MIT
source-code: https://github.com/picguard/picguard
issues: https://github.com/picguard/picguard/issues
website: https://www.kjxbyz.com/picguard
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

confinement: strict
base: core22
grade: stable

slots:
  dbus-picguard: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.kjxbyz.watermarkassistant # adjust accordingly to your app name and

apps:
  picguard:
    command: picguard
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
    slots:
      - dbus-picguard
parts:
  picguard:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    override-build: |
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
