name: Test Windows msix

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  msix:
    name: Create msix
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.6'

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Install certificates
        run: |
          echo $env:RUNNER_TEMP
          $env:CERTIFICATE_PATH = "$env:RUNNER_TEMP\picguard.pfx"
          echo $env:WINDOWS_CERTIFICATE | openssl base64 -d -out $env:CERTIFICATE_PATH
          (get-content windows\packaging\msix\make_config.yaml) -replace 'CERTIFICATE_PATH_PLACEHOLDER', $env:CERTIFICATE_PATH -replace 'CERTIFICATE_PASSWORD_PLACEHOLDER', $env:WINDOWS_CERTIFICATE_PASSWORD | Out-File -encoding ASCII windows\packaging\msix\make_config.yaml
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}

      - name: Build msix
        run: flutter_distributor package --platform windows --targets msix --artifact-name picguard.msix

      # Package the build.
      - name: Copy build for msix
        run: ls -R
        working-directory: dist

      - name: Clean up
        if: ${{ always() }}
        run: |
          ls
          echo "$env:RUNNER_TEMP\picguard.pfx"
          remove-item -Path "$env:RUNNER_TEMP\picguard.pfx" -Force -ErrorAction SilentlyContinue
          remove-item -Path "windows\packaging\msix\make_config.yaml" -Force -ErrorAction SilentlyContinue
