name: Test Snapcraft(arm64)

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  snap_arm64:
    name: Create snap(arm64)
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          group: lxd
          channel: latest/stable

      - name: Add user to the LXD (lxd) group
        run: |
          sudo usermod -a -G lxd ${USER}
          newgrp lxd

      - name: Configure .env
        run: |
          echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Install yq
        run: |
          if ! command -v yq >/dev/null 2>&1; then
            echo "yq not exists"
            sudo snap install -y yq
          fi
          yq --version

      - name: Update snapcraft.yaml
        run: |
          rm -f snap/snapcraft.yaml
          mv snap/snapcraft-arm64.yaml snap/snapcraft.yaml

      - name: Check LXD status
        run: lxc launch ubuntu:22.04 testlxd

      - name: Build snap
        run: |
          # https://snapcraft.io/docs/flutter-applications
          snapcraft --use-lxd

      # Package the build.
      - name: Copy build for snap
        run: ls -la *.snap

      - uses: actions/upload-artifact@v4
        with:
          name: snap-arm64-artifact
          path: |
            ./*.snap

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
          snapcraft clean
