name: Test Windows SignTool

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  signtool:
    name: Create signtool
    runs-on: windows-latest
    steps:
      - name: Check SignTool
        run: |
          cd 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool'
          ls -R
